create database ithingv;
use ithingv;

# --------------우선순위1----------------------
# 회원
CREATE TABLE MEMBER (
    M_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    M_MEMBER_ID TEXT NOT NULL UNIQUE,
    M_AUTH TEXT NOT NULL,
    M_NAME TEXT NOT NULL,
    M_BIRTH TEXT NULL,
    M_GENDER TEXT NULL,
    M_CREATED_DATETIME TEXT NOT NULL
);

# 공지사항
CREATE TABLE NOTICE (
    NT_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NT_TITLE TEXT NOT NULL,
    NT_CONTENT TEXT NULL,
    NT_WRITER TEXT NOT NULL,
    NT_CREATED_DATETIME TEXT NOT NULL
);

# --------------우선순위2----------------------
# 게시글

CREATE TABLE BOARD (
    BO_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BO_M_ID INTEGER NOT NULL,
    BO_TITLE TEXT NOT NULL,
    BO_CONTENT TEXT NULL,
    BO_CREATED_DATETIME TEXT NOT NULL,
    BO_MODIFIED_DATETIME TEXT NULL,
    FOREIGN KEY (BO_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE
);


# 명예 점수
CREATE TABLE HONOR_POINT (
    HP_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    HP_M_ID INTEGER NOT NULL,
    HP_SCORE INTEGER NULL DEFAULT 0,
    HP_CREATED_DATETIME TEXT NOT NULL,
    FOREIGN KEY (HP_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE
);


# 관심사
CREATE TABLE MEMBER_INTEREST (
    MI_M_ID INTEGER NOT NULL,
    MI_NAME TEXT NOT NULL,
    PRIMARY KEY (MI_M_ID, MI_NAME),
    FOREIGN KEY (MI_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# --------------우선순위3----------------------
# 게시글 이미지
CREATE TABLE BOARD_IMAGE (
    BOI_BO_ID INTEGER NOT NULL,
    BOI_IMG_URL TEXT NOT NULL,
    PRIMARY KEY (BOI_BO_ID, BOI_IMG_URL),
    FOREIGN KEY (BOI_BO_ID) REFERENCES BOARD(BO_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# 조회기록
CREATE TABLE VIEW_HISTORY (
    VH_M_ID INTEGER NOT NULL,
    VH_BO_ID INTEGER NOT NULL,
    VH_CREATED_DATETIME TEXT NOT NULL,
    PRIMARY KEY (VH_M_ID, VH_BO_ID),
    FOREIGN KEY (VH_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (VH_BO_ID) REFERENCES BOARD(BO_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# 댓글
CREATE TABLE BOARD_COMMENT (
    BC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BC_M_ID INTEGER NOT NULL,
    BC_BO_ID INTEGER NOT NULL,
    BC_CONTENT TEXT NULL,
    BC_CREATED_DATETIME TEXT NOT NULL,
    BC_MODIFIED_DATETIME TEXT NULL,
    FOREIGN KEY (BC_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (BC_BO_ID) REFERENCES BOARD(BO_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# 좋아요
CREATE TABLE BOARD_THUMBS_UP (
    BTU_M_ID INTEGER NOT NULL,
    BTU_BO_ID INTEGER NOT NULL,
    BTU_CREATED_DATETIME TEXT NOT NULL,
    PRIMARY KEY (BTU_M_ID, BTU_BO_ID),
    FOREIGN KEY (BTU_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (BTU_BO_ID) REFERENCES BOARD(BO_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# 싫어요
CREATE TABLE BOARD_THUMBS_DOWN (
    BTD_M_ID INTEGER NOT NULL,
    BTD_BO_ID INTEGER NOT NULL,
    BTD_CREATED_DATETIME TEXT NOT NULL,
    PRIMARY KEY (BTD_M_ID, BTD_BO_ID),
    FOREIGN KEY (BTD_M_ID) REFERENCES MEMBER(M_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (BTD_BO_ID) REFERENCES BOARD(BO_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
